appId = "dev.mapleleaf.screent"
files = ["dist/**/*", "assets/**/*"]

# can't import execa from inside the asar for some reason
asar = false

[directories]
output = "release"

[linux]
target = ["AppImage", "deb", "pacman"]
category = "Utility"
executableName = "screent"
icon = "assets/icon-604x604.png"
